<?php use App\Core\Security; ?>
<div class="max-w-7xl mx-auto">
    <div class="mb-6 flex items-start justify-between flex-wrap gap-3">
        <div>
            <h1 class="text-2xl font-bold text-white flex items-center gap-3">
                <svg class="w-7 h-7 text-aegisz-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg>
                Correlation Explorer
            </h1>
            <p class="text-gray-400 text-sm mt-1"><?= number_format($paginator->total) ?> correlation(s) · Generated by Intelligence Worker — read-only</p>
        </div>
        <?php if (!empty($bySeverity)): ?>
            <div class="flex gap-2 text-xs">
                <?php foreach (['critical'=>'aegisz-danger','high'=>'orange','medium'=>'aegisz-warning','low'=>'gray'] as $sev=>$col): ?>
                    <?php if (!empty($bySeverity[$sev])): ?>
                        <span class="px-2 py-1 rounded bg-<?= $col ?>-900/30 text-<?= $col ?>-400"><?= (int)$bySeverity[$sev] ?> <?= $sev ?></span>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

    <!-- Filters -->
    <form method="GET" action="<?= Security::e($baseUrl) ?>/correlations" class="mb-4 flex flex-wrap gap-2">
        <input type="text" name="q" value="<?= Security::e($q->search) ?>" placeholder="Search IOC, asset, explanation…"
               class="flex-1 min-w-64 bg-gray-800 border border-gray-700 text-gray-300 text-sm rounded-lg px-3 py-2 focus:outline-none focus:border-aegisz-accent">
        <select name="correlation_type" class="bg-gray-800 border border-gray-700 text-gray-300 text-sm rounded-lg px-3 py-2 focus:outline-none focus:border-aegisz-accent">
            <option value="">All Types</option>
            <?php foreach (['ioc_asset','ioc_alert','threat_incident'] as $t): ?>
                <option value="<?= $t ?>" <?= $q->filter('correlation_type')===$t?'selected':'' ?>><?= strtoupper(str_replace('_',' → ',$t)) ?></option>
            <?php endforeach; ?>
        </select>
        <select name="severity" class="bg-gray-800 border border-gray-700 text-gray-300 text-sm rounded-lg px-3 py-2 focus:outline-none focus:border-aegisz-accent">
            <option value="">All Severities</option>
            <?php foreach (['low','medium','high','critical'] as $v): ?><option value="<?= $v ?>" <?= $q->filter('severity')===$v?'selected':'' ?>><?= ucfirst($v) ?></option><?php endforeach; ?>
        </select>
        <select name="confidence_min" class="bg-gray-800 border border-gray-700 text-gray-300 text-sm rounded-lg px-3 py-2 focus:outline-none focus:border-aegisz-accent">
            <option value="">Any Confidence</option>
            <?php foreach ([50=>'>50%',70=>'>70%',80=>'>80%',90=>'>90%'] as $v=>$l): ?><option value="<?= $v ?>" <?= $q->filter('confidence_min')===(string)$v?'selected':'' ?>><?= $l ?></option><?php endforeach; ?>
        </select>
        <input type="date" name="date_from" value="<?= Security::e($q->filter('date_from')) ?>" class="bg-gray-800 border border-gray-700 text-gray-300 text-sm rounded-lg px-3 py-2 focus:outline-none focus:border-aegisz-accent">
        <input type="date" name="date_to" value="<?= Security::e($q->filter('date_to')) ?>" class="bg-gray-800 border border-gray-700 text-gray-300 text-sm rounded-lg px-3 py-2 focus:outline-none focus:border-aegisz-accent">
        <button type="submit" class="bg-gray-700 hover:bg-gray-600 text-white text-sm px-4 py-2 rounded-lg transition-colors">Search</button>
        <a href="<?= Security::e($baseUrl) ?>/correlations" class="text-sm text-gray-500 hover:text-white self-center">Clear</a>
    </form>

    <?php if (empty($correlations)): ?>
        <div class="bg-aegisz-panel border border-gray-700 rounded-lg p-12 text-center text-gray-500">
            <svg class="w-10 h-10 mx-auto mb-3 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            No correlations match your filters.
        </div>
    <?php else: ?>
        <div class="space-y-3">
            <?php foreach ($correlations as $corr): ?>
                <?php
                    $sevColor = ['low'=>'gray','medium'=>'aegisz-warning','high'=>'orange','critical'=>'aegisz-danger'][$corr['severity']]??'gray';
                    $typeLabel = str_replace('_',' → ',strtoupper($corr['correlation_type']??''));
                ?>
                <a href="<?= Security::e($baseUrl) ?>/correlations/detail?id=<?= (int)$corr['id'] ?>" class="block bg-aegisz-panel border border-gray-700 hover:border-aegisz-accent rounded-lg p-4 transition-colors">
                    <div class="flex items-start justify-between gap-4">
                        <div class="flex-1 min-w-0">
                            <div class="flex items-center gap-2 mb-2 flex-wrap">
                                <span class="text-xs font-mono text-aegisz-accent bg-aegisz-accent/10 px-2 py-0.5 rounded"><?= Security::e($typeLabel) ?></span>
                                <?php if (!empty($corr['ioc_value'])): ?><span class="text-xs font-mono text-gray-400"><?= Security::e(substr($corr['ioc_value'],0,40)) ?></span><?php endif; ?>
                                <?php if (!empty($corr['asset_name'])): ?><span class="text-xs text-gray-500">→ <?= Security::e($corr['asset_name']) ?></span><?php endif; ?>
                            </div>
                            <p class="text-sm text-gray-300 line-clamp-1"><?= Security::e($corr['explanation']) ?></p>
                        </div>
                        <div class="flex items-center gap-2 shrink-0">
                            <span class="text-xs text-gray-500"><?= (int)$corr['confidence'] ?>%</span>
                            <span class="px-2 py-0.5 rounded text-xs bg-<?= $sevColor ?>-900/30 text-<?= $sevColor ?>-400"><?= Security::e(ucfirst($corr['severity'])) ?></span>
                        </div>
                    </div>
                    <div class="text-xs text-gray-600 mt-2"><?= Security::e($corr['created_at']) ?></div>
                </a>
            <?php endforeach; ?>
        </div>
        <?php $view->partial('pagination', ['paginator' => $paginator, 'q' => $q]); ?>
    <?php endif; ?>
</div>
