<?php
/**
 * AegisZ Sentinel - Correlation Controller (v0.6.0)
 * Read-only Correlation Explorer. Correlations generated by Intelligence Worker only.
 */

namespace App\Controllers;

use App\Core\Security;
use App\Core\Session;
use App\Core\SearchQuery;
use App\Repositories\CorrelationRepository;

class CorrelationController extends BaseController
{
    private CorrelationRepository $corrRepo;

    public function __construct()
    {
        parent::__construct();
        $this->corrRepo = new CorrelationRepository();
    }

    /** GET /correlations */
    public function index(): void
    {
        $q      = SearchQuery::fromRequest($_GET, ['created_at','confidence','severity','correlation_type']);
        $result = $this->corrRepo->search($q);

        $this->render('correlations/index', [
            'title'      => 'Correlation Explorer | AegisZ Sentinel',
            'appName'    => 'AegisZ Sentinel',
            'version'    => '0.6.0',
            'correlations' => $result['data'],
            'paginator'  => $result['paginator'],
            'q'          => $q,
            'bySeverity' => $this->corrRepo->countBySeverity(),
            'byType'     => $this->corrRepo->countByType(),
        ]);
    }

    /** GET /correlations/detail?id=N */
    public function detail(): void
    {
        $id   = (int) ($_GET['id'] ?? 0);
        $corr = $this->corrRepo->findById($id);
        if (!$corr) {
            Session::flash('error', 'Correlation not found.');
            $this->redirect($this->baseUrl . '/correlations');
            return;
        }

        $linkedIOC      = $corr['ioc_id']      ? $this->corrRepo->getLinkedIOC((int) $corr['ioc_id'])           : null;
        $linkedAsset    = $corr['asset_id']    ? $this->corrRepo->getLinkedAsset((int) $corr['asset_id'])         : null;
        $linkedAlert    = $corr['alert_id']    ? $this->corrRepo->getLinkedAlert((int) $corr['alert_id'])         : null;
        $linkedIncident = $corr['incident_id'] ? $this->corrRepo->getLinkedIncident((int) $corr['incident_id'])   : null;

        $this->render('correlations/detail', [
            'title'         => "Correlation #{$id} | AegisZ Sentinel",
            'appName'       => 'AegisZ Sentinel',
            'version'       => '0.6.0',
            'corr'          => $corr,
            'linkedIOC'     => $linkedIOC,
            'linkedAsset'   => $linkedAsset,
            'linkedAlert'   => $linkedAlert,
            'linkedIncident'=> $linkedIncident,
        ]);
    }
}
